#!/usr/bin/env python3
import getpass
import json
from pathlib import Path

import server

ROOT = Path(__file__).resolve().parent
ENV_PATH = ROOT / ".env"


def read_env():
    values = {}
    if not ENV_PATH.exists():
        return values
    for line in ENV_PATH.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        values[key.strip()] = value.strip().strip('"').strip("'")
    return values


def write_env(values):
    lines = [
        "# Reporter local setup",
        "# Generated by setup.py. You can rerun setup.py to change these.",
        f"PORT={values.get('PORT', '8001')}",
        f"REPORTER_ADMIN_PASSWORD={values.get('REPORTER_ADMIN_PASSWORD', '')}",
        f"GOOGLE_CLIENT_ID={values.get('GOOGLE_CLIENT_ID', '')}",
        f"GOOGLE_CLIENT_SECRET={values.get('GOOGLE_CLIENT_SECRET', '')}",
        f"GOOGLE_REDIRECT_URI={values.get('GOOGLE_REDIRECT_URI', '')}",
        "",
    ]
    ENV_PATH.write_text("\n".join(lines))


def ask(prompt, current="", secret=False):
    suffix = f" [{current}]" if current else ""
    full_prompt = f"{prompt}{suffix}: "
    value = getpass.getpass(full_prompt) if secret else input(full_prompt)
    return value.strip() or current


def yes_no(prompt, default=True):
    marker = "Y/n" if default else "y/N"
    answer = input(f"{prompt} ({marker}): ").strip().lower()
    if not answer:
        return default
    return answer in ("y", "yes")


def main():
    print("\nReporter setup\n")
    env = read_env()
    server.init_db()
    with server.db() as conn:
        existing_cloud = json.loads(server.get_setting(conn, "cloud_storage") or "{}")

    port = ask("Port", env.get("PORT", "8001"))
    redirect_default = env.get("GOOGLE_REDIRECT_URI") or f"http://127.0.0.1:{port}/auth/google/callback"

    print("\nAdmin password")
    print("Leave blank to keep the current password if the database already exists.")
    password = ask("Admin password", "", secret=True)
    confirm = ""
    if password:
        confirm = ask("Confirm admin password", "", secret=True)
        if password != confirm:
            raise SystemExit("Passwords did not match. Setup cancelled.")

    print("\nGoogle Drive")
    print("For connect-once Drive, use OAuth Client ID + Client Secret from Google Cloud.")
    google_client_id = ask("Google Client ID", env.get("GOOGLE_CLIENT_ID", ""))
    google_client_secret = ask("Google Client Secret", env.get("GOOGLE_CLIENT_SECRET", ""), secret=True)
    google_redirect_uri = ask("Google Redirect URI", redirect_default)
    drive_folder_id = ask("Google Drive parent folder ID", existing_cloud.get("driveFolderId", ""))

    env.update(
        {
            "PORT": port,
            "REPORTER_ADMIN_PASSWORD": password or env.get("REPORTER_ADMIN_PASSWORD", ""),
            "GOOGLE_CLIENT_ID": google_client_id,
            "GOOGLE_CLIENT_SECRET": google_client_secret,
            "GOOGLE_REDIRECT_URI": google_redirect_uri,
        }
    )
    write_env(env)

    server.load_env()

    with server.db() as conn:
        if password:
            server.set_password(conn, password)
        existing_cloud.update(
            {
                "provider": "gdrive" if google_client_id else existing_cloud.get("provider", "local"),
                "driveClientId": google_client_id,
                "driveClientSecret": google_client_secret,
                "driveFolderId": drive_folder_id or existing_cloud.get("driveFolderId", ""),
            }
        )
        server.put_setting(conn, "cloud_storage", json.dumps(existing_cloud))

    print("\nSetup complete.")
    print(f"\nStart Reporter:\n  python3 server.py")
    print(f"\nOpen:\n  http://127.0.0.1:{port}/")
    if google_client_id and google_client_secret:
        print("\nConnect Google Drive once:")
        print(f"  http://127.0.0.1:{port}/auth/google/start")
        if "127.0.0.1" in google_redirect_uri or "localhost" in google_redirect_uri:
            print(f"\nIf running on a remote server, visit:")
            print(f"  http://<your-server-domain>:{port}/auth/google/start")
            print("\nAnd set GOOGLE_REDIRECT_URI to match your server address.")
        print("\nAdd this exact redirect URI in Google Cloud OAuth:")
        print(f"  {google_redirect_uri}")
        print("\nGoogle Cloud OAuth app type:")
        print("  Web application")
    print("")


if __name__ == "__main__":
    main()
